baseURL = "https://example.org/"
languageCode = "en-us"
title = "The Script Express"
theme = "navigator-hugo"
summaryLength = 10

# Build robots.txt file
enableRobotsTXT = true
# google analytics tracking id
googleAnalytics = "G-08VSER9BTL" # your analitics ID

enableGitInfo = false
pygmentsCodeFences = true

# Multilangues setup
# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
defaultContentLanguageInSubdir = true
DefaultContentLanguage = "en"

# Site Params
[params]
logo = "images/logo.png"

[[Params.listeLangues]]
code = "en"


############# 2 - Site en ENGLISH
[Languages.en]
weight = 1
languageCode = "en-us"
title = "The Script Express"
dateFormat = "January 2, 2006"
home = "Home"
logo = "images/logo.png"
menufixed = false

footerDescription = "The Script Express is a creative writing firm focussed on creating the experience. Also, our mascot is called Boo."
footerServiceTitle = "Service"
footerQuicklinkTitle = "Quicklinks"
footerAboutTitle = "About"
footerSubscribeTitle = "Mailing List"


# cookies
[params.cookies]
enable = true
expire_days = 2

# About 2 Section
[Languages.en.params.aboutSm]
enable  = true
title   = "Boo, our mascot welcomes you to our own creative writing firm, The Script Express."
description = "The Script Express is a creative writing firm focussed on creating the experience. We’ve worked with a number of international clients in the past-ghost writing ad films, documentaries, film scripts and social media campaigns. Proficiency in the English language is our forte, and we’ve developed a strong command of advertising, branding, content and design."

# Blog Section On Homepage
[Languages.en.params.blog]
enable  = false
topTitle= "OUR UNTOLD STORY"
title   = "Blog."
subtitle= "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"

# Contact Section
[Languages.en.params.contact]
enable  = true
topTitle= "DROP US A NOTE"
title   = "Contact Us."
subtitle= "Let's get in touch and let the world experience your ideas!"
address = "Artisans Lab, 78/103, Dr Radhakrishanan Salai, Mylapore, Chennai"
address1 = ""
phone   = ""
phone1 = ""
email   = ""
email1  = ""

# Site Menus
[menu]
# Navbar Menus
[[menu.nav]]
name    = "about"
url     = "about"
weight  = 2
[[menu.nav]]
name    = "service"
url     = "service"
weight  = 3
[[menu.nav]]
name    = "portfolio"
url     = "portfolio"
weight  = 4
[[menu.nav]]
name    = "contact"
url     = "contact"
weight  = 5

# Footer Service Menu
[[menu.service]]
name    = "graphicdesign"
url     = "service"
weight  = 1
[[menu.service]]
name    = "webdesign"
url     = "service"
weight  = 2
[[menu.service]]
name    = "webdevelopment"
url     = "service"
weight  = 3

# Footer Quick links Menu
[[menu.quicklink]]
name    = "partners"
url     = "about"
weight  = 1
[[menu.quicklink]]
name    = "about"
url     = "about"
weight  = 2
[[menu.quicklink]]
name    = "faqs"
url     = "about"
weight  = 3
[[menu.quicklink]]
name    = "badges"
url     = "about"
weight  = 4
